### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by andoniaf**
I've created this PR to solve #74  adding a docker image and a Makefile to run the docker image easily.

### CODE REVIEW

**Comment by DavidHernandez** [comment]
I tried this PR and did not work. When accessing the site, it showed me the standard NGINX page. I'm going to fork your branch to try to replace the site approach to use https://www.npmjs.com/package/metalsmith-watch to facilitate the development, as this docker image will not be used for deploying to production.

**Comment by DavidHernandez** [comment]
Ok, metalsmith-watch is broken, tried to fix it with no luck. Looking for alternatives.

**Comment by DavidHernandez** [comment]
I'm going to merge this PR to give you the credit for the work, @andoniaf.

**Comment by andoniaf** [comment]
> 
> 
> I'm going to merge this PR to give you the credit for the work, @andoniaf.

Perfect, thanks! 😄

**Pull request merged**
